### ISSUE TITLE
Causes crash.

### ISSUE THREAD

**Issue by ijiraq** [OSSOS/MOP#319]
bash-3.2$ python validate.py cands vos:OSSOS/measure3/2013B-L 
ERROR: AttributeError: 'NoneType' object has no attribute 'toggle_reticule' [ossos.fitsviewer.displayable]
Traceback (most recent call last):
  File "/Users/jjk/MOP_src/src/ossos-pipeline/ossos/gui/views/keybinds.py", line 111, in on_toggle_reticule
    self.controller.on_toggle_reticule_key()
  File "/Users/jjk/MOP_src/src/ossos-pipeline/ossos/gui/controllers.py", line 124, in on_toggle_reticule_key
    self.view.toggle_reticule()
  File "/Users/jjk/MOP_src/src/ossos-pipeline/ossos/gui/views/appview.py", line 30, in new_guithread_function
    return function(*args, **kwargs)
  File "/Users/jjk/MOP_src/src/ossos-pipeline/ossos/gui/views/appview.py", line 110, in toggle_reticule
    self.image_viewer.toggle_reticule()
  File "/Users/jjk/MOP_src/src/ossos-pipeline/ossos/fitsviewer/baseviewer.py", line 63, in toggle_reticule
    self.current_displayable.toggle_reticule()
  File "/Users/jjk/MOP_src/src/ossos-pipeline/ossos/fitsviewer/displayable.py", line 295, in toggle_reticule
    self.image_singlet.toggle_reticule()
  File "/Users/jjk/MOP_src/src/ossos-pipeline/ossos/fitsviewer/displayable.py", line 206, in toggle_reticule
    self.marker.toggle_reticule()

**Comment by mtbannister** [comment]
Toggle_reticule has since been re-enabled.
