### ISSUE TITLE
[MOP] ephemtarget unable to handle multiple targets

### ISSUE THREAD

**Issue by mtbannister** [OSSOS/MOP#339]
On trying to save an ephemeris-tracked pointing containing multiple targets, ephemtarget.append() throws the exception below. This is particularly pernicious as it only throws if the pointing contains more than one TNO. 
Astropy version is 0.2.4.

    [<ossos.orbfit.Orbfit object at 0x10f585e10>, <ossos.orbfit.Orbfit object at 0x10ed0b1d0>, <ossos.orbfit.Orbfit object at 0x10d7d4210>, <ossos.orbfit.Orbfit object at 0x10d79ed90>, <ossos.orbfit.Orbfit object at 0x10d78cad0>, <ossos.orbfit.Orbfit object at 0x10ed1d190>]
Exception in Tkinter callback
Traceback (most recent call last):
  File "/Applications/Canopy.app/appdata/canopy-1.0.3.1262.macosx-x86_64/Canopy.app/Contents/lib/python2.7/lib-tk/Tkinter.py", line 1410, in __call__
    return self.func(*args)
  File "../ossos-pipeline/src/ossos-pipeline/scripts/OSSOSplot.py", line 861, in save_pointings
    et.append(cc)
  File "/Users/michele/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/ossos/ephem_target.py", line 136, in append
    coord = ICRSCoordinates(sra+" "+sdec, unit=(units.hour, units.degree))
  File "/Users/michele/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/astropy/coordinates/builtin_systems.py", line 67, in __init__
    super(ICRSCoordinates, self)._initialize_latlon('ra', 'dec', True, args, kwargs)
  File "/Users/michele/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/astropy/coordinates/coordsystems.py", line 212, in _initialize_latlon
    latang = Dec(latval, unit=units[1])
  File "/Users/michele/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/astropy/coordinates/angles.py", line 561, in __init__
    super(Dec, self).__init__(angle, unit=unit, bounds=(-90, 90))
  File "/Users/michele/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/astropy/coordinates/angles.py", line 92, in __init__
    angle = util.dms_to_degrees(*angle)
  File "/Users/michele/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/astropy/coordinates/angle_utilities.py", line 348, in dms_to_degrees
    _check_second_range(s)
  File "/Users/michele/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/astropy/coordinates/angle_utilities.py", line 274, in _check_second_range
    warn(IllegalSecondWarning(sec, 'Treating as 0 sec, +1 min'))
NameError: global name 'IllegalSecondWarning' is not defined

**Comment by ijiraq** [comment]
resolved in 9179a1cde4b3148d779f4e968bcce09eb1e3780e
