### ISSUE TITLE
[reals] [refactor branch] On_do_accept not completing task

### ISSUE THREAD

**Issue by mtbannister** [OSSOS/MOP#351]
On trying to make a photometric measurement using reals, after hitting 'enter' on the standard MPC measurement gui window:

Traceback (most recent call last):
  File "/Users/bannisterm/lib/python2.7/site-packages/ossos-0.4.8-py2.7.egg/ossos/gui/views/validation.py", line 355, in _on_submit
    comment)
  File "/Users/bannisterm/lib/python2.7/site-packages/ossos-0.4.8-py2.7.egg/ossos/gui/controllers.py", line 421, in on_do_accept
    data.mpc_observations[key] = mpc_observation
AttributeError: 'AstromData' object has no attribute 'mpc_observations'

This prevents the measurement from being created and written to file.

**Comment by ijiraq** [comment]
This issues is resolved by commit  78ccf9c 

JJ

**Comment by mtbannister** [comment]
Closed by https://github.com/OSSOS/MOP/commit/78ccf9c70cbf789b6f56ab59c0cf0192067ab4fc
