### ISSUE TITLE
[refactor branch] [track] on_accept crashing due to lack of marker

### ISSUE THREAD

**Issue by mtbannister** [OSSOS/MOP#354]
On clicking the ds9 window to make a measurement on an image:

Traceback (most recent call last):
  File "/Users/bannisterm/Dropbox/OSSOS/ossos-pipeline/src/ossos/core/ossos/gui/views/keybinds.py", line 127, in on_accept_src_keybind
    self.controller.on_accept()
  File "/Users/bannisterm/Dropbox/OSSOS/ossos-pipeline/src/ossos/core/ossos/gui/controllers.py", line 532, in on_accept
    super(ProcessTracksController, self).on_accept(auto=False)
  File "/Users/bannisterm/Dropbox/OSSOS/ossos-pipeline/src/ossos/core/ossos/gui/controllers.py", line 254, in on_accept
    self.place_marker(ra, dec, radius=source_cutout.apcor.ap_in*0.185*units.arcsec, colour='green', force=True)
  File "/Users/bannisterm/Dropbox/OSSOS/ossos-pipeline/src/ossos/core/ossos/gui/controllers.py", line 53, in place_marker
    self.view.place_marker(self.model.get_current_cutout(), x, y, radius, colour=colour, force=force)
AttributeError: 'ApplicationView' object has no attribute 'place_marker'

**Comment by mtbannister** [comment]
Closed by https://github.com/OSSOS/MOP/commit/96f657e908ae0eff386710fe472f2e22ebc15540
