### ISSUE TITLE
[refactor branch] [track] error when no unmeasured lines available

### ISSUE THREAD

**Issue by mtbannister** [OSSOS/MOP#355]
When the file being attempted to arc-extend has no measurements left to add:

Traceback (most recent call last):
  File "../ossos-pipeline/src/ossos/core/tools/validate.py", line 77, in <module>
    main()
  File "../ossos-pipeline/src/ossos/core/tools/validate.py", line 68, in main
    args.username, args.skip_previous, args.zoom)
  File "../ossos-pipeline/src/ossos/core/tools/validate.py", line 22, in launch_app
    user_id=user_name, skip_previous=skip_previous, zoom=zoom)
  File "/Users/bannisterm/Dropbox/OSSOS/ossos-pipeline/src/ossos/core/ossos/gui/app.py", line 41, in create_application
    skip_previous=skip_previous, user_id=user_id, zoom=zoom)
  File "/Users/bannisterm/Dropbox/OSSOS/ossos-pipeline/src/ossos/core/ossos/gui/app.py", line 225, in __init__
    user_id=user_id, zoom=zoom)
  File "/Users/bannisterm/Dropbox/OSSOS/ossos-pipeline/src/ossos/core/ossos/gui/app.py", line 102, in __init__
    model.start_work()
  File "/Users/bannisterm/Dropbox/OSSOS/ossos-pipeline/src/ossos/core/ossos/gui/models/validation.py", line 40, in start_work
    self.next_workunit()
  File "/Users/bannisterm/Dropbox/OSSOS/ossos-pipeline/src/ossos/core/ossos/gui/models/validation.py", line 83, in next_workunit
    self._get_new_workunit()
  File "/Users/bannisterm/Dropbox/OSSOS/ossos-pipeline/src/ossos/core/ossos/gui/models/validation.py", line 114, in _get_new_workunit
    self.add_workunit(self.workunit_provider.get_workunit())
  File "/Users/bannisterm/Dropbox/OSSOS/ossos-pipeline/src/ossos/core/ossos/gui/models/workload.py", line 678, in get_workunit
    ignore_list=self.fetched_files)
  File "/Users/bannisterm/Dropbox/OSSOS/ossos-pipeline/src/ossos/core/ossos/gui/models/workload.py", line 596, in get_workunit
    self.directory_context.get_full_path(potential_file))
  File "/Users/bannisterm/Dropbox/OSSOS/ossos-pipeline/src/ossos/core/ossos/gui/models/workload.py", line 751, in build_workunit
    parsed_data = self.parser.parse(input_fullpath)
  File "/Users/bannisterm/Dropbox/OSSOS/ossos-pipeline/src/ossos/core/ossos/ssos.py", line 45, in parse
    self.ssos_parser = SSOSParser(mpc_observations[0].provisional_name,
IndexError: index 0 is out of bounds for axis 0 with size 0

**Comment by ijiraq** [comment]
Looks to me like this is caused by mpc_observations being a zero-length list.

From the previous line:

mpc_observations = mpc.MPCReader(filename).mpc_observations

That happens when there were no observations in the input file?


Could be there be a objectName.#.ast file that has no entries that is getting picked up?  


We could add a catch in the workload builder that errors gracefully at that point.

JJ

**Comment by mtbannister** [comment]
Resolved by successfully having astropy 1.1.2 installed.
